import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  // Global ignores first — must precede the next/core-web-vitals config
  // because FlatCompat's extends blocks later re-match *.ts/*.tsx files and
  // would otherwise override the ignore.
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "out/**",
      "build/**",
      "coverage/**",
      ".open-next/**",
      ".wrangler/**",
      "cloudflare-env.d.ts",
      "next-env.d.ts",
      // Auto-generated by `npm run db:types` from the live Supabase schema.
      // The packed-one-line output isn't hand-written and is meant to be
      // regenerated, not hand-fixed. Keep it out of lint and format.
      "src/lib/supabase/types.ts",
      // Auto-generated by `supabase start`. The local stack creates these
      // edge-runtime bundles on the fly; not our code.
      "supabase/.temp/**",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  ...compat.extends("prettier"),
  {
    files: ["src/**/*.{ts,tsx}"],
    ignores: ["**/app/api/**", "**/lib/supabase/server.ts"],
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          args: "all",
          argsIgnorePattern: "^_",
          caughtErrors: "all",
          caughtErrorsIgnorePattern: "^_",
          destructuredArrayIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          ignoreRestSiblings: true,
        },
      ],
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "next/headers",
              message: "Server-only; allowed only in app/api/** route handlers (issue #8).",
            },
          ],
        },
      ],
      "no-restricted-syntax": [
        "error",
        {
          selector: "Literal[value='use server']",
          message:
            "Server actions are forbidden (issue #8). Use a route handler under app/api/** instead.",
        },
        {
          selector: 'Literal[value="use server"]',
          message:
            "Server actions are forbidden (issue #8). Use a route handler under app/api/** instead.",
        },
      ],
    },
  },
  {
    // Billing provider boundary (issue #258, ADR 0002). The PaymentProvider
    // port is the only interface the app knows; vendor types must never leak
    // past src/lib/billing/adapters/. The registry is the composition root
    // and the sole exemption.
    //
    // Uses no-restricted-syntax rather than no-restricted-imports, which
    // would clobber the next/headers ban above for overlapping files (flat
    // config entries sharing a rule key overwrite). The use-server selectors
    // are repeated here for the same reason — omitting them would unban
    // server actions for every file this entry matches.
    // The path pattern matches both aliased/absolute imports
    // (`@/lib/billing/adapters/stub`) and relative ones (`./adapters/stub`,
    // `../adapters/stub`) — a domain file next to the adapters dir could
    // otherwise evade the boundary with a `./adapters/…` import.
    files: ["src/**/*.{ts,tsx}"],
    ignores: ["**/lib/billing/adapters/**", "**/lib/billing/registry.ts"],
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          selector: "Literal[value='use server']",
          message:
            "Server actions are forbidden (issue #8). Use a route handler under app/api/** instead.",
        },
        {
          selector: 'Literal[value="use server"]',
          message:
            "Server actions are forbidden (issue #8). Use a route handler under app/api/** instead.",
        },
        {
          selector: "ImportDeclaration[source.value=/billing\\/adapters|^\\.\\.?\\/adapters\\//]",
          message:
            "Provider adapters are behind the PaymentProvider port (issue #258, ADR 0002). Import the port from @/lib/billing/provider and resolve implementations via @/lib/billing/registry — never import an adapter directly.",
        },
        {
          selector:
            "ExportNamedDeclaration[source.value=/billing\\/adapters|^\\.\\.?\\/adapters\\//]",
          message:
            "Provider adapters are behind the PaymentProvider port (issue #258, ADR 0002). Re-export the port from @/lib/billing/provider instead — never re-export an adapter.",
        },
        {
          selector:
            "ExportAllDeclaration[source.value=/billing\\/adapters|^\\.\\.?\\/adapters\\//]",
          message:
            "Provider adapters are behind the PaymentProvider port (issue #258, ADR 0002). Re-export the port from @/lib/billing/provider instead — never re-export an adapter.",
        },
        {
          selector: "ImportExpression[source.value=/billing\\/adapters|^\\.\\.?\\/adapters\\//]",
          message:
            "Provider adapters are behind the PaymentProvider port (issue #258, ADR 0002). Resolve implementations via @/lib/billing/registry — never dynamically import an adapter.",
        },
      ],
    },
  },
];

export default eslintConfig;
