import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  // Global ignores first — must precede the next/core-web-vitals config
  // because FlatCompat's extends blocks later re-match *.ts/*.tsx files and
  // would otherwise override the ignore.
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "out/**",
      "build/**",
      "coverage/**",
      ".open-next/**",
      ".wrangler/**",
      "cloudflare-env.d.ts",
      "next-env.d.ts",
      // Auto-generated by `npm run db:types` from the live Supabase schema.
      // The packed-one-line output isn't hand-written and is meant to be
      // regenerated, not hand-fixed. Keep it out of lint and format.
      "src/lib/supabase/types.ts",
      // Auto-generated by `supabase start`. The local stack creates these
      // edge-runtime bundles on the fly; not our code.
      "supabase/.temp/**",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  ...compat.extends("prettier"),
  {
    files: ["src/**/*.{ts,tsx}"],
    ignores: ["**/app/api/**", "**/lib/supabase/server.ts"],
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          args: "all",
          argsIgnorePattern: "^_",
          caughtErrors: "all",
          caughtErrorsIgnorePattern: "^_",
          destructuredArrayIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          ignoreRestSiblings: true,
        },
      ],
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "next/headers",
              message: "Server-only; allowed only in app/api/** route handlers (issue #8).",
            },
          ],
        },
      ],
      "no-restricted-syntax": [
        "error",
        {
          selector: "Literal[value='use server']",
          message:
            "Server actions are forbidden (issue #8). Use a route handler under app/api/** instead.",
        },
        {
          selector: 'Literal[value="use server"]',
          message:
            "Server actions are forbidden (issue #8). Use a route handler under app/api/** instead.",
        },
      ],
    },
  },
];

export default eslintConfig;
