// Custom Cloudflare Worker entry for #155.
// OpenNext generates `.open-next/worker.js` with only a `fetch` handler.
// To add Cron Triggers we wrap that worker and add a `scheduled()` handler
// that dispatches on `event.cron` directly to business logic with a
// service-role client built from the Worker env — no HTTP round-trip to self.
//
// Pattern follows:
//   https://opennext.js.org/cloudflare/howtos/custom-worker
//   https://tomato3713.hatenablog.com/entry/2025/10/29/090000
//
// `wrangler.toml` main points here; `.open-next/worker.js` is still the
// source of truth for the Next.js fetch handler.

// generated by `opennextjs-cloudflare build`, not present at typecheck
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore — .open-next is generated after `next build`, so the import
// cannot be resolved during Next's typecheck. Wrangler bundles it at deploy.
import handler from "./.open-next/worker.js";
import { runFxRefresh } from "@/lib/fx/refresh";
import { generateAllInstances } from "@/lib/bill-instances";
import { runSendBillReminders } from "@/lib/cron/send-bill-reminders";
import { runPurgeHouseholds } from "@/lib/cron/purge-households";
import { createSupabaseCronClient } from "@/lib/supabase/cron";

// Minimal Cloudflare Worker types so `tsc --noEmit` passes without
// `@cloudflare/workers-types` or a generated `cloudflare-env.d.ts`.
// `wrangler types` will generate the real `CloudflareEnv` when deployed.
type Fetcher = { fetch(input: RequestInfo, init?: RequestInit): Promise<Response> };
type ExecutionContext = {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
};
type ExportedHandler<Env> = {
  fetch?: (request: Request, env: Env, ctx: ExecutionContext) => Promise<Response>;
  scheduled?: (
    event: { cron: string; scheduledTime: number },
    env: Env,
    ctx: ExecutionContext,
  ) => Promise<void>;
};
type CloudflareEnv = Record<string, unknown> & {
  ASSETS: Fetcher;
};

function populateProcessEnv(env: Record<string, unknown>) {
  for (const [key, value] of Object.entries(env)) {
    if (typeof value === "string") {
      (process.env as Record<string, string>)[key] = value;
    }
  }
}

// `event.cron` is the exact string from wrangler.toml `[triggers] crons`.
const CRON_MAP: Record<string, string> = {
  "0 6 * * *": "fx-refresh",
  "0 7 * * *": "generate-bill-instances",
  "0 12 * * *": "send-bill-reminders",
  "0 3 * * *": "purge-households",
};

// The shape Cloudflare delivers to `scheduled()`.
type ScheduledEvent = {
  cron: string;
  scheduledTime: number;
  noRetry?: () => void;
};

// Resolve the generated Next handler regardless of how OpenNext exports it.
const fetchHandler =
  (
    handler as unknown as {
      fetch?: (request: Request, env: CloudflareEnv, ctx: ExecutionContext) => Promise<Response>;
      default?: {
        fetch?: (request: Request, env: CloudflareEnv, ctx: ExecutionContext) => Promise<Response>;
      };
    }
  ).fetch ??
  (
    handler as unknown as {
      default: {
        fetch: (request: Request, env: CloudflareEnv, ctx: ExecutionContext) => Promise<Response>;
      };
    }
  ).default?.fetch;

if (!fetchHandler) {
  throw new Error("worker.ts: could not resolve fetch handler from .open-next/worker.js");
}

export default {
  async fetch(request: Request, env: CloudflareEnv, ctx: ExecutionContext): Promise<Response> {
    return fetchHandler(request, env, ctx);
  },

  async scheduled(event: ScheduledEvent, env: CloudflareEnv, ctx: ExecutionContext): Promise<void> {
    const job = CRON_MAP[event.cron];

    if (!job) {
      console.warn(`[scheduled] unrecognized cron "${event.cron}" — no job dispatched`);
      event.noRetry?.();
      return;
    }

    populateProcessEnv(env as Record<string, unknown>);

    const supabase = createSupabaseCronClient(env as Record<string, unknown>);

    console.info(`[scheduled] dispatching "${job}" for cron "${event.cron}"`);

    // Use `waitUntil` so the Worker stays alive for async DB/email work
    // even if the scheduled event's promise settlement is subtle across
    // workerd versions.
    const run = async () => {
      switch (job) {
        case "fx-refresh": {
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          const result = await runFxRefresh(supabase as any);
          console.info("[scheduled] fx-refresh result", result);
          break;
        }
        case "generate-bill-instances": {
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          const result = await generateAllInstances(supabase as any);
          const inserted = Object.values(result).reduce((s, c) => (c > 0 ? s + c : s), 0);
          console.info("[scheduled] generate-bill-instances", { inserted, details: result });
          break;
        }
        case "send-bill-reminders": {
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          const result = await runSendBillReminders(supabase as any);
          console.info("[scheduled] send-bill-reminders", result);
          break;
        }
        case "purge-households": {
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          const result = await runPurgeHouseholds(supabase as any);
          console.info("[scheduled] purge-households", result);
          break;
        }
        default:
          console.warn(`[scheduled] no handler for job "${job}"`);
      }
    };

    // Cloudflare recommends `ctx.waitUntil` for scheduled work; also await
    // so the invocation doesn't terminate early in `wrangler dev --test-scheduled`.
    // Non-retryable config errors (missing RESEND_API_KEY, Supabase env) should
    // not trigger Cloudflare's retry — call noRetry() and swallow the error.
    const promise = run().catch((err) => {
      const message = err instanceof Error ? err.message : String(err);
      const isNonRetryable =
        message.includes("RESEND_API_KEY") || message.includes("Supabase env not set");
      console.error(`[scheduled] "${job}" failed for cron "${event.cron}"`, err);
      if (isNonRetryable) {
        event.noRetry?.();
        return;
      }
      throw err;
    });
    ctx.waitUntil(promise);
    await promise;
  },
} satisfies ExportedHandler<CloudflareEnv>;

// Re-export Durable Object handlers if OpenNext generated them (R2 cache, etc.).
// They are not required for cron but must be re-exported when present so that
// bindings like WORKER_SELF_REFERENCE / NEXT_INC_CACHE_R2_BUCKET keep working.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const DOQueueHandler = (handler as any).DOQueueHandler;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const DOShardedTagCache = (handler as any).DOShardedTagCache;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const BucketCachePurge = (handler as any).BucketCachePurge;
