// Auto-generated by scripts/build-guide-content.mjs. Do not edit manually.

export type GuideFrontmatter = {
  title: string;
  slug: string;
  description: string;
  readingTime: number;
  updated: string;
  order: number;
  related: string[];
};

export type GuideHeading = {
  level: number;
  text: string;
  id: string;
};

export type GuideArticle = {
  frontmatter: GuideFrontmatter;
  headings: GuideHeading[];
  content: string;
};

export const ALL_GUIDE_SLUGS: string[] = [
  "leer-tu-primer-mes",
  "por-donde-empezar",
  "por-onde-comecar",
  "read-your-first-month",
  "starter-guide",
];

export const GUIDE_SLUGS_BY_LOCALE: Record<string, string[]> = {
  es: ["leer-tu-primer-mes", "por-donde-empezar"],
  en: ["read-your-first-month", "starter-guide"],
  "pt-BR": ["por-onde-comecar"],
};

export const GUIDE_ARTICLES: Record<string, Record<string, GuideArticle>> = {
  es: {
    "leer-tu-primer-mes": {
      frontmatter: {
        title: "Cómo leer tu primer mes de datos",
        slug: "leer-tu-primer-mes",
        description:
          "Cómo convertir tus primeras semanas de registros en una imagen clara — totales, categorías y qué hacer después.",
        readingTime: 6,
        updated: "2026-09-08",
        order: 2,
        related: ["por-donde-empezar"],
      },
      headings: [
        {
          level: 1,
          text: "Cómo leer tu primer mes de datos",
          id: "como-leer-tu-primer-mes-de-datos",
        },
        {
          level: 2,
          text: "El total del mes",
          id: "el-total-del-mes",
        },
        {
          level: 2,
          text: "Por categoría",
          id: "por-categoria",
        },
        {
          level: 2,
          text: "Qué no hacer todavía",
          id: "que-no-hacer-todavia",
        },
      ],
      content:
        "\n# Cómo leer tu primer mes de datos\n\nCon dos a cuatro semanas de registros, los números empiezan a contar una historia. Esta lección muestra cómo leerla sin complicarte.\n\n## El total del mes\n\nEn Análisis, selecciona el mes actual. El número destacado es tu neto — ingresos menos gastos — convertido a la moneda base del hogar.\n\n## Por categoría\n\nEl gráfico agrupa el gasto por categoría. Busca las dos o tres barras más altas — ahí un pequeño cambio tiene el mayor impacto.\n\n## Qué no hacer todavía\n\nNo crees una docena de presupuestos a la vez. Elige una o dos categorías que te sorprendieron y ponles un límite suave primero.\n",
    },
    "por-donde-empezar": {
      frontmatter: {
        title: "Por dónde empezar: guía de 5 minutos para ordenar tus finanzas",
        slug: "por-donde-empezar",
        description:
          "Una guía breve y práctica para registrar tus primeros gastos, entender qué vale la pena llevar y dejar los presupuestos para después.",
        readingTime: 5,
        updated: "2026-09-08",
        order: 1,
        related: [],
      },
      headings: [
        {
          level: 1,
          text: "Por dónde empezar: guía de 5 minutos para ordenar tus finanzas",
          id: "por-donde-empezar-guia-de-5-minutos-para-ordenar-tus-finanzas",
        },
        {
          level: 2,
          text: "Por qué registrar primero",
          id: "por-que-registrar-primero",
        },
        {
          level: 2,
          text: "El plan de siete días",
          id: "el-plan-de-siete-dias",
        },
        {
          level: 3,
          text: "Día 1: Anota una compra reciente",
          id: "dia-1-anota-una-compra-reciente",
        },
        {
          level: 3,
          text: "Día 2–3: Suma dos gastos más",
          id: "dia-23-suma-dos-gastos-mas",
        },
        {
          level: 3,
          text: "Día 4–5: Invita a tu pareja",
          id: "dia-45-invita-a-tu-pareja",
        },
        {
          level: 3,
          text: "Día 6–7: Observa, no juzgues",
          id: "dia-67-observa-no-juzgues",
        },
        {
          level: 2,
          text: "Qué ignorar por ahora",
          id: "que-ignorar-por-ahora",
        },
        {
          level: 2,
          text: "Siguiente paso",
          id: "siguiente-paso",
        },
      ],
      content:
        "\n# Por dónde empezar: guía de 5 minutos para ordenar tus finanzas\n\nRegistrar tus finanzas no tiene por qué ser complicado. Esta guía te lleva por los primeros pasos — en cinco minutos y sin presupuestos por ahora.\n\n## Por qué registrar primero\n\nUn presupuesto impuesto sin datos reales rara vez se cumple. Registrar al menos una o dos semanas de gastos te muestra dónde va el dinero antes de decidir cuánto asignar.\n\n- **Semana 1–2:** Solo registra. No limites, solo observa.\n- **Semana 3:** Mira totales por categoría y decide qué ajustar.\n\n## El plan de siete días\n\nUn inicio suave de siete días, sin rachas ni castigos por días sin registro.\n\n### Día 1: Anota una compra reciente\n\nAbre DuoBalance y registra una compra reciente — café, supermercado, transporte. Tarda segundos.\n\n### Día 2–3: Suma dos gastos más\n\nSuma uno o dos gastos por día. Verás tu saldo actualizarse y las categorías tomar forma.\n\n### Día 4–5: Invita a tu pareja\n\nDesde Configuración → Miembros del hogar puedes invitar a tu pareja. Revisen juntos una vez al mes, no cada compra.\n\n### Día 6–7: Observa, no juzgues\n\nAl cerrar la semana, abre Análisis y revisa tus totales. Solo observa — no es momento de corregir todo.\n\n## Qué ignorar por ahora\n\nDurante estas dos semanas puedes ignorar la pestaña Presupuesto. Crear límites sin datos es adivinar. Vuelve a ella cuando tengas números reales.\n\n## Siguiente paso\n\nCuando tengas una semana de datos, pasa a [cómo leer tu primer mes](/guia/leer-tu-primer-mes) — pero solo si terminaste esta guía. No hay prisa.\n",
    },
  },
  en: {
    "read-your-first-month": {
      frontmatter: {
        title: "Reading your first month of data",
        slug: "read-your-first-month",
        description:
          "How to turn your first weeks of entries into a clear picture — totals, categories and what to do next.",
        readingTime: 6,
        updated: "2026-09-08",
        order: 2,
        related: ["starter-guide"],
      },
      headings: [
        {
          level: 1,
          text: "Reading your first month of data",
          id: "reading-your-first-month-of-data",
        },
        {
          level: 2,
          text: "The monthly total",
          id: "the-monthly-total",
        },
        {
          level: 2,
          text: "By category",
          id: "by-category",
        },
        {
          level: 2,
          text: "What not to do yet",
          id: "what-not-to-do-yet",
        },
      ],
      content:
        "\n# Reading your first month of data\n\nOnce you have two to four weeks of entries, the numbers start to tell a story. This lesson shows how to read it without overthinking.\n\n## The monthly total\n\nIn Reports, select the current month. The headline number is your net — income minus expenses — converted to your household's base currency.\n\n## By category\n\nThe bar chart groups spending by category. Look for the two or three biggest bars — that's where a small change has the biggest effect.\n\n## What not to do yet\n\nDon't set a dozen budgets at once. Pick the one or two categories that surprised you and set a soft limit there first.\n",
    },
    "starter-guide": {
      frontmatter: {
        title: "Where to start: a 5-minute guide to getting your finances in order",
        slug: "starter-guide",
        description:
          "A short, practical guide to logging your first expenses, understanding what's worth tracking, and leaving budgets for later.",
        readingTime: 5,
        updated: "2026-09-08",
        order: 1,
        related: [],
      },
      headings: [
        {
          level: 1,
          text: "Where to start: a 5-minute guide to getting your finances in order",
          id: "where-to-start-a-5-minute-guide-to-getting-your-finances-in-order",
        },
        {
          level: 2,
          text: "Why track first",
          id: "why-track-first",
        },
        {
          level: 2,
          text: "A seven-day plan",
          id: "a-seven-day-plan",
        },
        {
          level: 3,
          text: "Day 1: Log a recent purchase",
          id: "day-1-log-a-recent-purchase",
        },
        {
          level: 3,
          text: "Day 2–3: Add two more",
          id: "day-23-add-two-more",
        },
        {
          level: 3,
          text: "Day 4–5: Invite your partner",
          id: "day-45-invite-your-partner",
        },
        {
          level: 3,
          text: "Day 6–7: Observe, don't judge",
          id: "day-67-observe-dont-judge",
        },
        {
          level: 2,
          text: "What to ignore for now",
          id: "what-to-ignore-for-now",
        },
        {
          level: 2,
          text: "Next step",
          id: "next-step",
        },
      ],
      content:
        "\n# Where to start: a 5-minute guide to getting your finances in order\n\nTracking your money doesn't have to be complicated. This guide walks you through the first steps — in five minutes and without budgets for now.\n\n## Why track first\n\nA budget set without real data rarely sticks. Logging one or two weeks of spending shows you where the money goes before you decide how much to allocate.\n\n- **Week 1–2:** Just record. Don't limit, just observe.\n- **Week 3:** Look at totals by category and decide what to adjust.\n\n## A seven-day plan\n\nA gentle seven-day start — no streaks, no penalties for missed days.\n\n### Day 1: Log a recent purchase\n\nOpen DuoBalance and log a recent purchase — coffee, groceries, transit. It takes seconds.\n\n### Day 2–3: Add two more\n\nAdd one or two expenses per day. You'll see your balances update and categories take shape.\n\n### Day 4–5: Invite your partner\n\nFrom Settings → Household members you can invite your partner. Do a monthly review together, not a per-purchase check.\n\n### Day 6–7: Observe, don't judge\n\nAt the end of the week, open Reports and look at your totals. Just observe — this isn't the moment to fix everything.\n\n## What to ignore for now\n\nFor these two weeks you can ignore the Budget tab. Creating limits without data is guessing. Come back when you have real numbers.\n\n## Next step\n\nWhen you have a week of data, read how to [read your first month](/guide/read-your-first-month) — but only if you finished this guide. No rush.\n",
    },
  },
  "pt-BR": {
    "por-onde-comecar": {
      frontmatter: {
        title: "Por onde começar: guia de 5 minutos para organizar suas finanças",
        slug: "por-onde-comecar",
        description:
          "Um guia curto e prático para registrar seus primeiros gastos, entender o que vale a pena acompanhar e deixar orçamentos para depois.",
        readingTime: 5,
        updated: "2026-09-08",
        order: 1,
        related: [],
      },
      headings: [
        {
          level: 1,
          text: "Por onde começar: guia de 5 minutos para organizar suas finanças",
          id: "por-onde-comecar-guia-de-5-minutos-para-organizar-suas-financas",
        },
        {
          level: 2,
          text: "Por que registrar primeiro",
          id: "por-que-registrar-primeiro",
        },
        {
          level: 2,
          text: "Plano de sete dias",
          id: "plano-de-sete-dias",
        },
      ],
      content:
        "\n# Por onde começar: guia de 5 minutos para organizar suas finanças\n\nRegistrar suas finanças não precisa ser complicado. Este guia leva você pelos primeiros passos — em cinco minutos e sem orçamentos por enquanto.\n\n## Por que registrar primeiro\n\nUm orçamento sem dados reais raramente funciona. Registrar uma ou duas semanas de gastos mostra para onde o dinheiro vai antes de decidir quanto alocar.\n\n## Plano de sete dias\n\nUm começo suave de sete dias, sem sequências ou punições por dias perdidos.\n",
    },
  },
};
