// Auto-generated by scripts/build-guide-content.mjs. Do not edit manually.

import { ARTICLES_ES } from "./generated/es";
import { ARTICLES_EN } from "./generated/en";
import { ARTICLES_PT_BR } from "./generated/pt-BR";

export type GuideFrontmatter = {
  title: string;
  slug: string;
  description: string;
  readingTime: number;
  updated: string;
  order: number;
  related: string[];
};

export type GuideHeading = {
  level: number;
  text: string;
  id: string;
};

export type GuideArticle = {
  frontmatter: GuideFrontmatter;
  headings: GuideHeading[];
  content: string;
  html: string;
};

export const ALL_GUIDE_SLUGS: string[] = [
  "armar-tu-presupuesto",
  "build-your-budget",
  "leer-tu-primer-mes",
  "por-donde-empezar",
  "por-onde-comecar",
  "read-your-first-month",
  "starter-guide",
];

export const GUIDE_SLUGS_BY_LOCALE: Record<string, string[]> = {
  es: ["armar-tu-presupuesto", "leer-tu-primer-mes", "por-donde-empezar"],
  en: ["build-your-budget", "read-your-first-month", "starter-guide"],
  "pt-BR": ["por-onde-comecar"],
};

export const GUIDE_ARTICLES: Record<string, Record<string, GuideArticle>> = {
  es: ARTICLES_ES,
  en: ARTICLES_EN,
  "pt-BR": ARTICLES_PT_BR,
};
