// Auto-generated by scripts/build-help-content.mjs. Do not edit manually.

import { ARTICLES_ES } from "./generated/es";
import { ARTICLES_EN } from "./generated/en";
import { ARTICLES_PT_BR } from "./generated/pt-BR";

export type ArticleFrontmatter = {
  title: string;
  slug: string;
  category: string;
  order: number;
  related: string[];
  updated: string;
};

export type ArticleHeading = {
  level: number;
  text: string;
  id: string;
};

export type Article = {
  frontmatter: ArticleFrontmatter;
  headings: ArticleHeading[];
  content: string;
  html: string;
};

export const ALL_HELP_SLUGS: string[] = [
  "adding-accounts",
  "balance-looks-wrong",
  "bill-reminders-not-arriving",
  "categories-and-auto-rules",
  "exchange-rates-stale",
  "exporting-your-data",
  "getting-started-creating-household",
  "household-vs-personal-budgets",
  "installing-on-mobile",
  "inviting-your-partner",
  "ledger-vs-manual-balance",
  "managing-households-and-members",
  "mobile-navigation-and-quick-entry",
  "multi-currency-and-exchange-rates",
  "number-format-currency-timezone",
  "privacy-what-we-can-and-cant-see",
  "private-accounts-and-views",
  "reading-the-charts",
  "recording-transaction-fast",
  "recurrence-and-marking-paid",
  "transfers-arent-expenses",
  "who-spent-vs-who-typed",
];

export const HELP_ARTICLES: Record<string, Record<string, Article>> = {
  es: ARTICLES_ES,
  en: ARTICLES_EN,
  "pt-BR": ARTICLES_PT_BR,
};
