// Auto-generated by scripts/build-help-content.mjs. Do not edit manually.

export type ArticleFrontmatter = {
  title: string;
  slug: string;
  category: string;
  order: number;
  related: string[];
  updated: string;
};

export type ArticleHeading = {
  level: number;
  text: string;
  id: string;
};

export type Article = {
  frontmatter: ArticleFrontmatter;
  headings: ArticleHeading[];
  content: string;
};

export const ALL_HELP_SLUGS: string[] = [
  "household-vs-personal-budgets",
  "ledger-vs-manual-balance",
  "number-format-currency-timezone",
  "private-accounts-and-views",
  "reading-the-charts",
  "recurrence-and-marking-paid",
  "who-spent-vs-who-typed",
];

export const HELP_ARTICLES: Record<string, Record<string, Article>> = {
  es: {
    "ledger-vs-manual-balance": {
      frontmatter: {
        title: "¿Por qué mi saldo no cuadra? Modo saldo manual vs. libro diario",
        slug: "ledger-vs-manual-balance",
        category: "accounts",
        order: 1,
        related: ["private-accounts-and-views", "who-spent-vs-who-typed"],
        updated: "2026-08-15",
      },
      headings: [
        {
          level: 1,
          text: "Modo saldo manual vs. libro diario",
          id: "modo-saldo-manual-vs-libro-diario",
        },
        {
          level: 2,
          text: "Modo Libro Diario (Ledger)",
          id: "modo-libro-diario-ledger",
        },
        {
          level: 2,
          text: "Modo Saldo Manual",
          id: "modo-saldo-manual",
        },
        {
          level: 2,
          text: "Cómo cambiar de modo",
          id: "cmo-cambiar-de-modo",
        },
      ],
      content:
        "\n# Modo saldo manual vs. libro diario\n\nEn duobalance cada cuenta puede funcionar en uno de dos modos de saldo: **Libro diario (Ledger)** o **Manual**.\n\n## Modo Libro Diario (Ledger)\n\nEn el modo Libro Diario, el saldo actual de la cuenta se calcula automáticamente sumando el saldo inicial más todas las transacciones asociadas a la cuenta.\n\n- **Cuándo usarlo:** Para cuentas principales donde registras cada gasto, ingreso o transferencia.\n- **Por qué podría no cuadrar:** Si falta alguna transacción o el saldo inicial configurado no era correcto.\n\n## Modo Saldo Manual\n\nEn el modo Manual, tú defines directamente cuál es el saldo actual de la cuenta actualizándolo periódicamente.\n\n- **Cuándo usarlo:** Para tarjetas de crédito, cuentas de inversión o cuentas secundarias donde no deseas registrar cada café o compra pequeña.\n- **Transacciones en modo manual:** Puedes registrar transacciones para que sumen a los presupuestos y reportes, pero dichas transacciones no alteran automáticamente el saldo fijado manualmente.\n\n## Cómo cambiar de modo\n\n1. Dirígete a **Saldos** o **Ajustes de Cuenta**.\n2. Haz clic en la cuenta que deseas modificar.\n3. Selecciona el modo de saldo preferido y guarda los cambios.\n",
    },
    "private-accounts-and-views": {
      frontmatter: {
        title: "Cuentas privadas y visibilidad de saldos",
        slug: "private-accounts-and-views",
        category: "accounts",
        order: 2,
        related: ["ledger-vs-manual-balance", "household-vs-personal-budgets"],
        updated: "2026-08-15",
      },
      headings: [
        {
          level: 1,
          text: "Cuentas privadas y visibilidad de saldos",
          id: "cuentas-privadas-y-visibilidad-de-saldos",
        },
        {
          level: 2,
          text: "Vistas: Todo, Mis cuentas y Compartidas",
          id: "vistas-todo-mis-cuentas-y-compartidas",
        },
        {
          level: 2,
          text: "¿Por qué mi pareja y yo vemos totales diferentes?",
          id: "por-qu-mi-pareja-y-yo-vemos-totales-diferentes",
        },
        {
          level: 2,
          text: "Transacciones privadas en Presupuestos",
          id: "transacciones-privadas-en-presupuestos",
        },
      ],
      content:
        '\n# Cuentas privadas y visibilidad de saldos\n\nEn duobalance puedes elegir qué cuentas son compartidas con el hogar y cuáles son privadas.\n\n## Vistas: Todo, Mis cuentas y Compartidas\n\n- **Compartida (Shared):** Ambos miembros del hogar pueden ver el saldo, historial y transacciones de esta cuenta.\n- **Privada (Mine):** Solo el propietario de la cuenta puede ver el saldo detallado y los movimientos individuales.\n\n## ¿Por qué mi pareja y yo vemos totales diferentes?\n\nSi tienes una cuenta privada, tu total personal (vista "Todo" o "Mío") incluirá tus fondos privados, mientras que la vista de tu pareja no los incluirá. Esto es por diseño para respetar la privacidad financiera individual dentro del hogar.\n\n## Transacciones privadas en Presupuestos\n\nLas transacciones realizadas desde una cuenta privada aún pueden asignarse a presupuestos del hogar si tú decides categorizarlas como gasto compartido.\n',
    },
    "who-spent-vs-who-typed": {
      frontmatter: {
        title: "¿Quién gastó vs. quién lo registró?",
        slug: "who-spent-vs-who-typed",
        category: "transactions",
        order: 3,
        related: ["ledger-vs-manual-balance", "transfers-and-expenses"],
        updated: "2026-08-15",
      },
      headings: [
        {
          level: 1,
          text: "¿Quién gastó vs. quién lo registró?",
          id: "quin-gast-vs-quin-lo-registr",
        },
        {
          level: 2,
          text: "¿Por qué existe esta distinción?",
          id: "por-qu-existe-esta-distincin",
        },
        {
          level: 2,
          text: "Corrección de atribución",
          id: "correccin-de-atribucin",
        },
      ],
      content:
        '\n# ¿Quién gastó vs. quién lo registró?\n\nAl registrar un movimiento en duobalance, distinguimos entre **Quién gastó (spent_by)** y **Quién registró (entered_by)**.\n\n## ¿Por qué existe esta distinción?\n\nEs muy común que una persona ingrese los recibos o facturas de ambas personas al final del día o de la semana.\n\n- **Gastado por (spent_by):** Indica de quién fue la compra o responsabilidad. Se utiliza para filtrar reportes personales y presupuestos individuales.\n- **Registrado por (entered_by):** Se asigna automáticamente al usuario con la sesión activa que creó la transacción.\n\n## Corrección de atribución\n\nPuedes editar una transacción existente en cualquier momento para cambiar la opción "Gastado por" si fue asignada incorrectamente.\n',
    },
    "household-vs-personal-budgets": {
      frontmatter: {
        title: "Presupuestos del hogar vs. presupuestos personales",
        slug: "household-vs-personal-budgets",
        category: "budgets",
        order: 4,
        related: ["private-accounts-and-views", "reading-the-charts"],
        updated: "2026-08-15",
      },
      headings: [
        {
          level: 1,
          text: "Presupuestos del hogar vs. presupuestos personales",
          id: "presupuestos-del-hogar-vs-presupuestos-personales",
        },
        {
          level: 2,
          text: "Presupuestos del Hogar",
          id: "presupuestos-del-hogar",
        },
        {
          level: 2,
          text: "Presupuestos Personales",
          id: "presupuestos-personales",
        },
        {
          level: 2,
          text: "Cambiar de pestaña",
          id: "cambiar-de-pestaa",
        },
      ],
      content:
        "\n# Presupuestos del hogar vs. presupuestos personales\n\nduobalance te permite organizar los presupuestos en dos alcances: **Del Hogar** y **Mis Presupuestos**.\n\n## Presupuestos del Hogar\n\nAfectan los gastos compartidos del hogar (por ejemplo, alimentación, servicios, vivienda). Ambas personas contribuyen al límite y ven el progreso conjunto.\n\n## Presupuestos Personales\n\nSon privados para cada miembro (por ejemplo, pasatiempos o cuidado personal). Te permiten controlar tus gastos individuales sin interferir en los límites globales de la pareja.\n\n## Cambiar de pestaña\n\nUtiliza el selector en la parte superior de la pantalla de Presupuestos para alternar entre la vista **Hogar** y **Mío**.\n",
    },
    "recurrence-and-marking-paid": {
      frontmatter: {
        title: "Facturas recurrentes y marcar como pagado",
        slug: "recurrence-and-marking-paid",
        category: "bills",
        order: 5,
        related: ["who-spent-vs-who-typed", "bill-reminders-troubleshooting"],
        updated: "2026-08-15",
      },
      headings: [
        {
          level: 1,
          text: "Facturas recurrentes y marcar como pagado",
          id: "facturas-recurrentes-y-marcar-como-pagado",
        },
        {
          level: 2,
          text: "Configuración de recurrencia",
          id: "configuracin-de-recurrencia",
        },
        {
          level: 2,
          text: "Marcar como pagado",
          id: "marcar-como-pagado",
        },
      ],
      content:
        "\n# Facturas recurrentes y marcar como pagado\n\nLa sección de Facturas te ayuda a dar seguimiento a compromisos fijos y periódicos como alquiler, suscripciones o servicios públicos.\n\n## Configuración de recurrencia\n\nAl crear una factura, puedes elegir el ciclo de repetición (mensual, quincenal, anual, etc.). duobalance generará automáticamente la instancia correspondiente para cada periodo.\n\n## Marcar como pagado\n\nCuando pagas una factura:\n\n1. Haz clic en la factura pendiente.\n2. Selecciona **Marcar como pagado**.\n3. Elige si deseas crear automáticamente una transacción de gasto vinculada a una de tus cuentas.\n",
    },
    "reading-the-charts": {
      frontmatter: {
        title: "¿Cómo interpretar los gráficos y reportes?",
        slug: "reading-the-charts",
        category: "reports",
        order: 6,
        related: ["household-vs-personal-budgets", "multi-currency-exchange-rates"],
        updated: "2026-08-15",
      },
      headings: [
        {
          level: 1,
          text: "¿Cómo interpretar los gráficos y reportes?",
          id: "cmo-interpretar-los-grficos-y-reportes",
        },
        {
          level: 2,
          text: "Gráfico por categorías",
          id: "grfico-por-categoras",
        },
        {
          level: 2,
          text: "Evolución mensual e ingresos vs. gastos",
          id: "evolucin-mensual-e-ingresos-vs-gastos",
        },
        {
          level: 2,
          text: "Conversión de moneda en reportes",
          id: "conversin-de-moneda-en-reportes",
        },
      ],
      content:
        "\n# ¿Cómo interpretar los gráficos y reportes?\n\nLa sección de Reportes convierte tus transacciones en visión financiera clara para el hogar.\n\n## Gráfico por categorías\n\nMuestra en qué categorías se concentra la mayor parte de tus gastos en el rango de fechas seleccionado.\n\n## Evolución mensual e ingresos vs. gastos\n\nCompara el flujo total de entradas y salidas mes a mes.\n\n- **Barras verdes:** Ingresos totales.\n- **Barras rojas:** Gastos totales.\n\n## Conversión de moneda en reportes\n\nTodos los montos se convierten a la moneda base de tu hogar utilizando los tipos de cambio registrados en la fecha correspondiente.\n",
    },
    "number-format-currency-timezone": {
      frontmatter: {
        title: "Configuración de moneda, formato de números y zona horaria",
        slug: "number-format-currency-timezone",
        category: "settings",
        order: 7,
        related: ["multi-currency-exchange-rates", "stale-exchange-rates"],
        updated: "2026-08-15",
      },
      headings: [
        {
          level: 1,
          text: "Configuración de moneda, formato de números y zona horaria",
          id: "configuracin-de-moneda-formato-de-nmeros-y-zona-horaria",
        },
        {
          level: 2,
          text: "Moneda Base del Hogar",
          id: "moneda-base-del-hogar",
        },
        {
          level: 2,
          text: "Formato de Números",
          id: "formato-de-nmeros",
        },
        {
          level: 2,
          text: "Zona Horaria",
          id: "zona-horaria",
        },
      ],
      content:
        "\n# Configuración de moneda, formato de números y zona horaria\n\nPuedes personalizar la manera en que duobalance muestra los montos y fechas en la sección **Ajustes**.\n\n## Moneda Base del Hogar\n\nEs la moneda principal en la que se calculan los totales y reportes del hogar.\n\n## Formato de Números\n\nElige entre separadores con punto (`1.234,56`) o con coma (`1,234.56`) según tus preferencias regionales.\n\n## Zona Horaria\n\nAsegura que los cierres de mes y las fechas de facturas se calculen según tu hora local.\n",
    },
  },
  en: {
    "ledger-vs-manual-balance": {
      frontmatter: {
        title: "Why is my balance incorrect? Ledger vs. manual balance mode",
        slug: "ledger-vs-manual-balance",
        category: "accounts",
        order: 1,
        related: ["private-accounts-and-views", "who-spent-vs-who-typed"],
        updated: "2026-08-15",
      },
      headings: [
        {
          level: 1,
          text: "Ledger vs. manual balance mode",
          id: "ledger-vs-manual-balance-mode",
        },
        {
          level: 2,
          text: "Ledger Mode",
          id: "ledger-mode",
        },
        {
          level: 2,
          text: "Manual Balance Mode",
          id: "manual-balance-mode",
        },
        {
          level: 2,
          text: "How to switch modes",
          id: "how-to-switch-modes",
        },
      ],
      content:
        "\n# Ledger vs. manual balance mode\n\nIn duobalance each account operates in one of two balance modes: **Ledger** or **Manual**.\n\n## Ledger Mode\n\nIn Ledger mode, the account balance is computed automatically from the opening balance plus all transactions linked to that account.\n\n- **When to use:** For main accounts where you record every expense, income, or transfer.\n- **Why it might differ:** If a transaction is missing or the initial balance was set incorrectly.\n\n## Manual Balance Mode\n\nIn Manual mode, you directly set the current balance by updating it periodically.\n\n- **When to use:** For credit cards, investment accounts, or secondary accounts where you don't want to track every small purchase.\n- **Transactions in manual mode:** You can still log transactions so they count toward budgets and reports, but they won't automatically alter the manually set balance.\n\n## How to switch modes\n\n1. Go to **Balances** or **Account Settings**.\n2. Tap the account you wish to modify.\n3. Select your preferred balance mode and save changes.\n",
    },
    "private-accounts-and-views": {
      frontmatter: {
        title: "Private accounts and balance visibility",
        slug: "private-accounts-and-views",
        category: "accounts",
        order: 2,
        related: ["ledger-vs-manual-balance", "household-vs-personal-budgets"],
        updated: "2026-08-15",
      },
      headings: [
        {
          level: 1,
          text: "Private accounts and balance visibility",
          id: "private-accounts-and-balance-visibility",
        },
        {
          level: 2,
          text: "Views: All, Mine, and Shared",
          id: "views-all-mine-and-shared",
        },
        {
          level: 2,
          text: "Why do my partner and I see different totals?",
          id: "why-do-my-partner-and-i-see-different-totals",
        },
        {
          level: 2,
          text: "Private transactions in Budgets",
          id: "private-transactions-in-budgets",
        },
      ],
      content:
        '\n# Private accounts and balance visibility\n\nIn duobalance you can choose which accounts are shared with the household and which remain private.\n\n## Views: All, Mine, and Shared\n\n- **Shared:** Both members of the household can view the balance, history, and transactions.\n- **Private (Mine):** Only the account owner can view detailed balances and individual movements.\n\n## Why do my partner and I see different totals?\n\nIf you have a private account, your personal total ("All" or "Mine" view) will include your private funds, while your partner\'s view will not. This is by design to respect individual financial privacy within the household.\n\n## Private transactions in Budgets\n\nTransactions made from a private account can still be assigned to household budgets if you choose to categorize them as a shared expense.\n',
    },
    "who-spent-vs-who-typed": {
      frontmatter: {
        title: "Who spent it vs. who recorded it?",
        slug: "who-spent-vs-who-typed",
        category: "transactions",
        order: 3,
        related: ["ledger-vs-manual-balance", "transfers-and-expenses"],
        updated: "2026-08-15",
      },
      headings: [
        {
          level: 1,
          text: "Who spent it vs. who recorded it?",
          id: "who-spent-it-vs-who-recorded-it",
        },
        {
          level: 2,
          text: "Why distinguish between them?",
          id: "why-distinguish-between-them",
        },
        {
          level: 2,
          text: "Correcting attribution",
          id: "correcting-attribution",
        },
      ],
      content:
        '\n# Who spent it vs. who recorded it?\n\nWhen logging a transaction in duobalance, we distinguish between **Who spent it (spent_by)** and **Who recorded it (entered_by)**.\n\n## Why distinguish between them?\n\nIt is very common for one partner to enter receipts or invoices for both people at the end of the day or week.\n\n- **Spent by (spent_by):** Indicates whose purchase or responsibility it was. Used for personal reports and individual budgets.\n- **Recorded by (entered_by):** Automatically assigned to the active user who created the transaction entry.\n\n## Correcting attribution\n\nYou can edit an existing transaction at any time to change the "Spent by" selection if it was misassigned.\n',
    },
    "household-vs-personal-budgets": {
      frontmatter: {
        title: "Household vs. personal budgets",
        slug: "household-vs-personal-budgets",
        category: "budgets",
        order: 4,
        related: ["private-accounts-and-views", "reading-the-charts"],
        updated: "2026-08-15",
      },
      headings: [
        {
          level: 1,
          text: "Household vs. personal budgets",
          id: "household-vs-personal-budgets",
        },
        {
          level: 2,
          text: "Household Budgets",
          id: "household-budgets",
        },
        {
          level: 2,
          text: "Personal Budgets",
          id: "personal-budgets",
        },
        {
          level: 2,
          text: "Switching tabs",
          id: "switching-tabs",
        },
      ],
      content:
        "\n# Household vs. personal budgets\n\nduobalance lets you organize budgets into two scopes: **Household** and **Mine**.\n\n## Household Budgets\n\nTrack shared household spending (such as groceries, utilities, rent). Both partners contribute to the limit and see joint progress.\n\n## Personal Budgets\n\nPrivate to each member (such as hobbies or personal care). They let you manage individual spending without affecting shared household targets.\n\n## Switching tabs\n\nUse the tab selector at the top of the Budgets screen to toggle between **Household** and **Mine**.\n",
    },
    "recurrence-and-marking-paid": {
      frontmatter: {
        title: "Recurring bills and marking paid",
        slug: "recurrence-and-marking-paid",
        category: "bills",
        order: 5,
        related: ["who-spent-vs-who-typed", "bill-reminders-troubleshooting"],
        updated: "2026-08-15",
      },
      headings: [
        {
          level: 1,
          text: "Recurring bills and marking paid",
          id: "recurring-bills-and-marking-paid",
        },
        {
          level: 2,
          text: "Recurrence configuration",
          id: "recurrence-configuration",
        },
        {
          level: 2,
          text: "Marking as paid",
          id: "marking-as-paid",
        },
      ],
      content:
        "\n# Recurring bills and marking paid\n\nThe Bills section helps you track fixed, recurring commitments like rent, subscriptions, or utilities.\n\n## Recurrence configuration\n\nWhen creating a bill, choose the repetition frequency (monthly, biweekly, annually, etc.). duobalance generates the corresponding instance for each period automatically.\n\n## Marking as paid\n\nWhen paying a bill:\n\n1. Tap the pending bill instance.\n2. Select **Mark as paid**.\n3. Choose whether to automatically log a linked expense transaction in one of your accounts.\n",
    },
    "reading-the-charts": {
      frontmatter: {
        title: "How to read charts and reports",
        slug: "reading-the-charts",
        category: "reports",
        order: 6,
        related: ["household-vs-personal-budgets", "multi-currency-exchange-rates"],
        updated: "2026-08-15",
      },
      headings: [
        {
          level: 1,
          text: "How to read charts and reports",
          id: "how-to-read-charts-and-reports",
        },
        {
          level: 2,
          text: "Category Breakdown Chart",
          id: "category-breakdown-chart",
        },
        {
          level: 2,
          text: "Monthly Trends & Income vs. Expense",
          id: "monthly-trends-income-vs-expense",
        },
        {
          level: 2,
          text: "Currency conversion in reports",
          id: "currency-conversion-in-reports",
        },
      ],
      content:
        "\n# How to read charts and reports\n\nThe Reports section turns your transactions into clear financial insights for the household.\n\n## Category Breakdown Chart\n\nShows where most of your expenses are concentrated for the selected date range.\n\n## Monthly Trends & Income vs. Expense\n\nCompares total cash inflow and outflow month by month.\n\n- **Green bars:** Total income.\n- **Red bars:** Total expenses.\n\n## Currency conversion in reports\n\nAll amounts are converted to your household's base currency using exchange rates on the transaction date.\n",
    },
    "number-format-currency-timezone": {
      frontmatter: {
        title: "Currency, number format, and timezone settings",
        slug: "number-format-currency-timezone",
        category: "settings",
        order: 7,
        related: ["multi-currency-exchange-rates", "stale-exchange-rates"],
        updated: "2026-08-15",
      },
      headings: [
        {
          level: 1,
          text: "Currency, number format, and timezone settings",
          id: "currency-number-format-and-timezone-settings",
        },
        {
          level: 2,
          text: "Household Base Currency",
          id: "household-base-currency",
        },
        {
          level: 2,
          text: "Number Format",
          id: "number-format",
        },
        {
          level: 2,
          text: "Timezone",
          id: "timezone",
        },
      ],
      content:
        "\n# Currency, number format, and timezone settings\n\nYou can customize how duobalance presents numbers and dates in the **Settings** section.\n\n## Household Base Currency\n\nThe primary currency used to calculate household totals and reports.\n\n## Number Format\n\nChoose between period separators (`1,234.56`) or comma separators (`1.234,56`) according to your regional preference.\n\n## Timezone\n\nEnsures month cutoffs and bill due dates are calculated according to your local time.\n",
    },
  },
  "pt-BR": {
    "ledger-vs-manual-balance": {
      frontmatter: {
        title: "Modo de saldo manual vs. livro diário",
        slug: "ledger-vs-manual-balance",
        category: "accounts",
        order: 1,
        related: ["private-accounts-and-views", "who-spent-vs-who-typed"],
        updated: "2026-08-15",
      },
      headings: [
        {
          level: 1,
          text: "Modo de saldo manual vs. livro diário",
          id: "modo-de-saldo-manual-vs-livro-dirio",
        },
        {
          level: 2,
          text: "Modo Livro Diário (Ledger)",
          id: "modo-livro-dirio-ledger",
        },
        {
          level: 2,
          text: "Modo Saldo Manual",
          id: "modo-saldo-manual",
        },
      ],
      content:
        "\n# Modo de saldo manual vs. livro diário\n\nNo duobalance, cada conta funciona em um de dois modos de saldo: **Livro diário (Ledger)** ou **Manual**.\n\n## Modo Livro Diário (Ledger)\n\nO saldo atual da conta é calculado automaticamente somando o saldo inicial e todas as transações associadas.\n\n- **Quando usar:** Para contas principais onde você registra cada gasto, receita ou transferência.\n- **Por que pode divergirem:** Se faltar alguma transação ou se o saldo inicial não estiver correto.\n\n## Modo Saldo Manual\n\nVocê define diretamente qual é o saldo atual atualizando-o periodicamente.\n\n- **Quando usar:** Cartões de crédito, contas de investimento ou secundárias.\n",
    },
    "private-accounts-and-views": {
      frontmatter: {
        title: "Contas privadas e visibilidade de saldos",
        slug: "private-accounts-and-views",
        category: "accounts",
        order: 2,
        related: ["ledger-vs-manual-balance", "household-vs-personal-budgets"],
        updated: "2026-08-15",
      },
      headings: [
        {
          level: 1,
          text: "Contas privadas e visibilidade de saldos",
          id: "contas-privadas-e-visibilidade-de-saldos",
        },
        {
          level: 2,
          text: "Visões: Tudo, Minhas e Compartilhadas",
          id: "vises-tudo-minhas-e-compartilhadas",
        },
      ],
      content:
        "\n# Contas privadas e visibilidade de saldos\n\nNo duobalance você escolhe quais contas são compartilhadas e quais são privadas.\n\n## Visões: Tudo, Minhas e Compartilhadas\n\n- **Compartilhada:** Ambos os parceiros podem ver saldo e movimentações.\n- **Privada (Minhas):** Apenas o proprietário visualiza detalhes do saldo.\n",
    },
    "who-spent-vs-who-typed": {
      frontmatter: {
        title: "Quem gastou vs. quem registrou?",
        slug: "who-spent-vs-who-typed",
        category: "transactions",
        order: 3,
        related: ["ledger-vs-manual-balance", "transfers-and-expenses"],
        updated: "2026-08-15",
      },
      headings: [
        {
          level: 1,
          text: "Quem gastou vs. quem registrou?",
          id: "quem-gastou-vs-quem-registrou",
        },
      ],
      content:
        "\n# Quem gastou vs. quem registrou?\n\nDistinguimos entre **Quem gastou (spent_by)** e **Quem registrou (entered_by)**.\n\n- **Gasto por:** Identifica de quem foi a despesa.\n- **Registrado por:** O usuário que criou o registro.\n",
    },
    "household-vs-personal-budgets": {
      frontmatter: {
        title: "Orçamentos da casa vs. pessoais",
        slug: "household-vs-personal-budgets",
        category: "budgets",
        order: 4,
        related: ["private-accounts-and-views", "reading-the-charts"],
        updated: "2026-08-15",
      },
      headings: [
        {
          level: 1,
          text: "Orçamentos da casa vs. pessoais",
          id: "oramentos-da-casa-vs-pessoais",
        },
      ],
      content:
        "\n# Orçamentos da casa vs. pessoais\n\nOs orçamentos são divididos em **Da Casa** e **Meus Orçamentos**.\n\n- **Da Casa:** Gastos compartilhados.\n- **Pessoais:** Privados para cada parceiro.\n",
    },
    "recurrence-and-marking-paid": {
      frontmatter: {
        title: "Contas recorrentes e marcar como pago",
        slug: "recurrence-and-marking-paid",
        category: "bills",
        order: 5,
        related: ["who-spent-vs-who-typed", "bill-reminders-troubleshooting"],
        updated: "2026-08-15",
      },
      headings: [
        {
          level: 1,
          text: "Contas recorrentes e marcar como pago",
          id: "contas-recorrentes-e-marcar-como-pago",
        },
        {
          level: 2,
          text: "Marcar como pago",
          id: "marcar-como-pago",
        },
      ],
      content:
        "\n# Contas recorrentes e marcar como pago\n\nGerencie compromissos fixos e recorrentes como aluguel e contas de luz.\n\n## Marcar como pago\n\nAo pagar uma conta, marque como pago e crie automaticamente a transação correspondente.\n",
    },
    "reading-the-charts": {
      frontmatter: {
        title: "Como ler os gráficos e relatórios",
        slug: "reading-the-charts",
        category: "reports",
        order: 6,
        related: ["household-vs-personal-budgets", "multi-currency-exchange-rates"],
        updated: "2026-08-15",
      },
      headings: [
        {
          level: 1,
          text: "Como ler os gráficos e relatórios",
          id: "como-ler-os-grficos-e-relatrios",
        },
      ],
      content:
        "\n# Como ler os gráficos e relatórios\n\nAcompanhe os gastos por categoria e a evolução mensal de receitas vs. despesas.\n",
    },
    "number-format-currency-timezone": {
      frontmatter: {
        title: "Configurações de moeda, formato de números e fuso horário",
        slug: "number-format-currency-timezone",
        category: "settings",
        order: 7,
        related: ["multi-currency-exchange-rates", "stale-exchange-rates"],
        updated: "2026-08-15",
      },
      headings: [
        {
          level: 1,
          text: "Configurações de moeda, formato de números e fuso horário",
          id: "configuraes-de-moeda-formato-de-nmeros-e-fuso-horrio",
        },
      ],
      content:
        "\n# Configurações de moeda, formato de números e fuso horário\n\nPersonalize a moeda base da casa, o formato numérico e o fuso horário na tela de Configurações.\n",
    },
  },
};
